<?php

$lang = array(

    "title-page" => "ITedup | Image and Brand",
    "title-loading" => "ITEDUP DIGITAL AGENCY",
    "titulo-primera-seccion" => "Corporate Image and Brand Design",
    "subtitulo-primera-seccion" => "We are experts in branding.",
    "boton-paquetes-primera-seccion" => "SEE PACKAGES",

    "titulo-segunda-seccion" => "Packages",
    "subtitulo-segunda-seccion" => "Choose the package you need",
    "titulo-tarjeta-primera" => "Basic",
    "tarjeta1-cuerpo-titulo1" => "Logo",
    "tarjeta1-cuerpo-descripcion1" => "5 Proposals, 10 Reviews",
    "tarjeta1-cuerpo-titulo2" => "Brand Guide",
    "tarjeta1-cuerpo-descripcion2" => "5 Slides",
    "tarjeta1-cuerpo-titulo3" => "Business cards",
    "tarjeta1-cuerpo-descripcion2" => "x1000, 4x4, laminated",
    "tarjeta1-footer-precio1" => "$300.98",
    "tarjeta1-footer-descuento1" => "You save $41.60",
    "titulo-tarjeta-segunda" => "Advanced",
    "tarjeta2-cuerpo-titulo1" => "Logo",
    "tarjeta2-cuerpo-descripcion1" => "5 Proposals, 10 Reviews",
    "tarjeta2-cuerpo-titulo2" => "Brand Guide",
    "tarjeta2-cuerpo-descripcion2" => "5 Slides",
    "tarjeta2-cuerpo-titulo3" => "Business cards",
    "tarjeta2-cuerpo-descripcion3" => "x1000, 4x4, laminated",
    "tarjeta2-cuerpo-titulo4" => "Frills",
    "tarjeta2-cuerpo-descripcion4" => "1/4 Letter, x1000, 4x4",
    "tarjeta2-cuerpo-titulo5" => "Social media",
    "tarjeta2-cuerpo-descripcion5" => "2 or 3 accounts",
    "tarjeta2-cuerpo-titulo6" => "Email Signature",
    "tarjeta2-cuerpo-descripcion6" => "Simple",
    "tarjeta2-footer-precio2" => "$411.10",
    "tarjeta2-footer-descuento2" => "You save $102.77",

    "titulo-tarjeta-tercera" => "Premium",
    "tarjeta3-cuerpo-titulo1" => "Logo",
    "tarjeta3-cuerpo-descripcion1" => "5 Proposals, 10 Reviews",
    "tarjeta3-cuerpo-titulo2" => "Brand Guide",
    "tarjeta3-cuerpo-descripcion2" => "10 Slides",
    "tarjeta3-cuerpo-titulo3" => "Business Presentation",
    "tarjeta3-cuerpo-descripcion3" => "10 Slides",
    "tarjeta3-cuerpo-titulo4" => "Business cards",
    "tarjeta3-cuerpo-descripcion4" => "x1000, 4x4, laminated",
    "tarjeta3-cuerpo-titulo5" => "Frills",
    "tarjeta3-cuerpo-descripcion5" => "1/4 Letter, x1000, 4x4",
    "tarjeta3-cuerpo-titulo6" => "Social media",
    "tarjeta3-cuerpo-descripcion6" => "4 or 5 accounts",
    "tarjeta3-cuerpo-titulo7" => "Email Signature",
    "tarjeta3-cuerpo-descripcion7" => "Advanced",
    "tarjeta3-footer-precio3" => "$822.20",
    "tarjeta3-footer-descuento3" => "You save $352.37",

    "titulo-tercera-seccion" => "Work process",
    "titulo1-tab1-tercera-seccion" => "1.- Inspiration",
    "descripcion1-tab1-tercera-seccion" => "In a session with the client, we talked about the project and looked for examples for the proposals. We investigate the competition, selection of colors and fonts and possible isotypes.",
    "descripcion2-tab1-tercera-seccion" => "With the information collected, we proceed to create the proposals. Depending on its complexity, a proposal can take 2 to 4 hours to complete.",
    "titulo2-tab2-tercera-seccion" => "2.- Reviews",
    "descripcion1-tab2-tercera-seccion" => "We show the proposal and begin a cycle of reviews, where we analyze the proposal and discuss the details to improve it.",
    "descripcion2-tab2-tercera-seccion" => "Depending on the complexity, a review cycle can take up to 2 hours to improve the proposal.",
    "titulo3-tab3-tercera-seccion" => "3.- Delivery",
    "descripcion1-tab3-tercera-seccion" => "When we obtain authorization and complete customer satisfaction, in a compressed file, we deliver the logo in its original and editable file in all formats and with all its elements.",
    "lista1-tab3-tercera-seccion" => "Formats",
    "lista1-1-tab3-tercera-seccion" => "Editable (.ai, .psd)",
    "lista1-2-tab3-tercera-seccion" => "Presentation (.pdf)",
    "lista1-3-tab3-tercera-seccion" => "For use (.png, .svg, .eps, .jpg)",
    "lista2-tab3-tercera-seccion" => "Implemented fonts",
    "lista3-tab3-tercera-seccion" => "Implemented colors",

    "titulo-cuarta-seccion" => "Testimonios",
    "subtitulo-cuarta-seccion" => "Our work",
    "descripcion1-testimonio" => "I love my logo! I have received plugins and am always happy to recommend them.",
    "nombre1-testimonio" => "Mitchel Govea",
    "puesto1-testimonio" => "Founder",

    "en" => "English",
    "es" => "Spanish",
    "it" => "Italian"

)
?>