<?php

$lang = array(

    "title-page" => "ITedup | Imagen y Marca",
    "title-loading" => "ITEDUP AGENCIA DIGITAL",
    "titulo-primera-seccion" => "Imagen Corporativa y Diseño de Marca",
    "subtitulo-primera-seccion" => "Somos expertos en creación de marcas.",
    "boton-paquetes-primera-seccion" => "VER PAQUETES",

    "titulo-segunda-seccion" => "Paquetes",
    "subtitulo-segunda-seccion" => "Escoge el paquete que necesites",
    "titulo-tarjeta-primera" => "Básico",
    "tarjeta1-cuerpo-titulo1" => "Logotipo",
    "tarjeta1-cuerpo-descripcion1" => "5 Propuestas, 10 Revisiones",
    "tarjeta1-cuerpo-titulo2" => "Guía de Marca",
    "tarjeta1-cuerpo-descripcion2" => "5 Slides",
    "tarjeta1-cuerpo-titulo3" => "Tarjetas de presentación",
    "tarjeta1-cuerpo-descripcion2" => "x1000, 4x4, laminadas",
    "tarjeta1-footer-precio1" => "$6,150",
    "tarjeta1-footer-descuento1" => "Ahorras $850",
    "titulo-tarjeta-segunda" => "Avanzado",
    "tarjeta2-cuerpo-titulo1" => "Logotipo",
    "tarjeta2-cuerpo-descripcion1" => "5 Propuestas, 10 Revisiones",
    "tarjeta2-cuerpo-titulo2" => "Guía de Marca",
    "tarjeta2-cuerpo-descripcion2" => "5 Slides",
    "tarjeta2-cuerpo-titulo3" => "Tarjetas de presentación",
    "tarjeta2-cuerpo-descripcion3" => "x1000, 4x4, laminadas",
    "tarjeta2-cuerpo-titulo4" => "Volantes",
    "tarjeta2-cuerpo-descripcion4" => "1/4 Carta, x1000, 4x4",
    "tarjeta2-cuerpo-titulo5" => "Redes Sociales",
    "tarjeta2-cuerpo-descripcion5" => "2 o 3 cuentas",
    "tarjeta2-cuerpo-titulo6" => "Firma de Email",
    "tarjeta2-cuerpo-descripcion6" => "Sencilla",
    "tarjeta2-footer-precio2" => "$8,400",
    "tarjeta2-footer-descuento2" => "Ahorras $2,100",

    "titulo-tarjeta-tercera" => "Premium",
    "tarjeta3-cuerpo-titulo1" => "Logotipo",
    "tarjeta3-cuerpo-descripcion1" => "5 Propuestas, 10 Revisiones",
    "tarjeta3-cuerpo-titulo2" => "Guía de Marca",
    "tarjeta3-cuerpo-descripcion2" => "10 Slides",
    "tarjeta3-cuerpo-titulo3" => "Presentación Empresarial",
    "tarjeta3-cuerpo-descripcion3" => "10 Slides",
    "tarjeta3-cuerpo-titulo4" => "Tarjetas de presentación",
    "tarjeta3-cuerpo-descripcion4" => "x1000, 4x4, laminadas",
    "tarjeta3-cuerpo-titulo5" => "Volantes",
    "tarjeta3-cuerpo-descripcion5" => "1/4 Carta, x1000, 4x4",
    "tarjeta3-cuerpo-titulo6" => "Redes Sociales",
    "tarjeta3-cuerpo-descripcion6" => "4 o 5 cuentas",
    "tarjeta3-cuerpo-titulo7" => "Firma de Email",
    "tarjeta3-cuerpo-descripcion7" => "Avanzada",
    "tarjeta3-footer-precio3" => "$16,800",
    "tarjeta3-footer-descuento3" => "Ahorras $7,200",

    "titulo-tercera-seccion" => "Proceso de Trabajo",
    "titulo1-tab1-tercera-seccion" => "1.- Inspiración",
    "descripcion1-tab1-tercera-seccion" => "En una sesión junto con el cliente, platicamos del proyecto y buscamos ejemplos para las propuestas. Investigamos a la competencia, selección de colores y tipografías y posibles isotipos.",
    "descripcion2-tab1-tercera-seccion" => "Con la información recaudada, procedemos a crear las propuestas. Dependiendo de su complejidad, una propuesta puede tomar en completar de 2 a 4 horas.",
    "titulo2-tab2-tercera-seccion" => "2.- Revisiones",
    "descripcion1-tab2-tercera-seccion" => "Mostramos la propuesta y comenzamos un ciclo de revisiones, en donde analizamos la propuesta y platicamos de los detalles para mejorarlo.",
    "descripcion2-tab2-tercera-seccion" => "Dependiendo de la complejidad, un ciclo de revisiones puede tomar hasta 2 horas para mejorar la propuesta.",
    "titulo3-tab3-tercera-seccion" => "3.- Entrega",
    "descripcion1-tab3-tercera-seccion" => "Cuando obtenemos la autorización y completa satisfacción del cliente, en un archivo comprimido, entregamos el logotipo en su archivo original y editable en todos los formatos y con todos sus elementos.",
    "lista1-tab3-tercera-seccion" => "Formatos",
    "lista1-1-tab3-tercera-seccion" => "Editables (.ai, .psd)",
    "lista1-2-tab3-tercera-seccion" => "Presentación (.pdf)",
    "lista1-3-tab3-tercera-seccion" => "Para uso (.png, .svg, .eps, .jpg)",
    "lista2-tab3-tercera-seccion" => "Tipografías implementadas",
    "lista3-tab3-tercera-seccion" => "Colores implementados",

    "titulo-cuarta-seccion" => "Testimonials",
    "subtitulo-cuarta-seccion" => "Nuestro Trabajo",
    "descripcion1-testimonio" => "¡Me encanta mi logotipo! He recibido complementos y siempre estoy feliz en recomendarlos.",
    "nombre1-testimonio" => "Mitchel Govea",
    "puesto1-testimonio" => "Fundador",

    "en" => "Ingles",
    "es" => "Español",
    "it" => "Italiano"

)
?>